sudo: required
dist: trusty
language: node_js
node_js:
- "6.9.2"
rvm:
- 2.3.4
before_install:
- sudo apt-get -qq update
- sudo apt-get install wget python-setuptools lsof unzip imagemagick ruby ruby-dev libnss3 libnss3-dev xvfb libnss3-1d libexif-dev curl build-essential libssl-dev -y
- rvm --default use 2.3.4
# environment
- export PATH=/tmp/bundler/ruby/2.3.0/bin:$PATH
- export GEM_PATH=/tmp/bundler/ruby/2.3.0/gems:$GEM_PATH
# xvfb
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# google chrome
- sudo apt-get -qq update
- sudo apt-get install chromium-browser -y
- export CHROME_BIN=/usr/bin/chromium-browser
- chromium-browser --no-sandbox &
# chromedriver
- wget http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- sudo chmod a+x /usr/local/bin/chromedriver
- chromedriver --port=9516 >/dev/null 2>/dev/null &
# ruby / bundler / rspec
- cd test && bundle install --path=/tmp/bundler && cd -
before_script:
# - npm run start:dev &
# - sleep 5
# script: cd test && bundle exec rspec tests.spec
# after_script:
# - echo 'Done!' 
